version: '3'

services:
  database:
    image: arm64v8/postgres
    restart: always
    ports:
      - ${DATASOURCE_PORT}:5432
    environment:
      - POSTGRES_PASSWORD=${DATASOURCE_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
